services:
  jenkins:
    image: jenkins/jenkins:lts-jdk17
    user: root
    ports:
      - 8080:8080
      - 50000:50000
    volumes:
          - ./reports/master:/var/jenkins_home


#  899cf93c0a844056a5fc81ef74b12a69






# Start from the official Jenkinsfile LTS image with JDK 11
#FROM jenkins/jenkins:2.414.2-jdk11
#
## Switch to root user to install packages
#USER root
#
## Add Dockerâ€™s official GPG key
#RUN curl -fsSLo /usr/share/keyrings/docker-archive-keyring.asc \
#  https://download.docker.com/linux/debian/gpg
#
## Set up the Docker repository for Debian
#RUN echo "deb [arch=$(dpkg --print-architecture) \
#  signed-by=/usr/share/keyrings/docker-archive-keyring.asc] \
#  https://download.docker.com/linux/debian \
#  $(lsb_release -cs) stable" > /etc/apt/sources.list.d/docker.list
#
## Install the Docker CLI inside the Jenkinsfile container
#RUN apt-get update && apt-get install -y docker-ce-cli
#
## Switch back to the Jenkinsfile user
#USER jenkins
#
## Install Jenkinsfile plugins (Blue Ocean UI and Docker pipeline support)
#RUN jenkins-plugin-cli --plugins "blueocean:1.25.3 docker-workflow:1.28"
## Default Jenkinsfile entrypoint
#ENTRYPOINT ["/usr/bin/tini", "--", "/usr/local/bin/jenkins.sh"]
